#!/bin/bash

CHECKER=../_build/default/rscheck.bc

GUARD_TESTS="x x+1 x+y x+y*2-a[z+1]"
ACTION_TESTS="x:=1 x:=y+1 t[i]:=i+1"

for e in $GUARD_TESTS
do
   echo "$e -> $($CHECKER -guard $e)"
done

for a in $ACTION_TESTS
do
   echo "$a -> $($CHECKER -action $a)"
done
